// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeleteResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type SingleRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRequest) Reset()         { *m = SingleRequest{} }
func (m *SingleRequest) String() string { return proto.CompactTextString(m) }
func (*SingleRequest) ProtoMessage()    {}
func (*SingleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *SingleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRequest.Unmarshal(m, b)
}
func (m *SingleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRequest.Marshal(b, m, deterministic)
}
func (m *SingleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRequest.Merge(m, src)
}
func (m *SingleRequest) XXX_Size() int {
	return xxx_messageInfo_SingleRequest.Size(m)
}
func (m *SingleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRequest proto.InternalMessageInfo

func (m *SingleRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Order struct {
	ID                   uint32               `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Order) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteResponse)(nil), "api.DeleteResponse")
	proto.RegisterType((*SingleRequest)(nil), "api.SingleRequest")
	proto.RegisterType((*Order)(nil), "api.Order")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x14, 0x84, 0x95, 0x40, 0x23, 0xf5, 0x41, 0x3a, 0x3c, 0x24, 0x54, 0x65, 0x69, 0x94, 0xa9, 0x93,
	0x2b, 0xca, 0xc2, 0xc0, 0x46, 0x06, 0x98, 0x10, 0x86, 0x3f, 0xe0, 0xc6, 0x8f, 0xc8, 0x92, 0x1b,
	0x1b, 0xdb, 0xe1, 0xf7, 0x23, 0x5e, 0x68, 0x69, 0xb7, 0xf3, 0xdd, 0xf9, 0xf4, 0xd9, 0x50, 0x46,
	0x0a, 0xdf, 0xa6, 0x23, 0xe1, 0x83, 0x4b, 0x0e, 0x2f, 0x94, 0x37, 0xd5, 0xaa, 0x77, 0xae, 0xb7,
	0xb4, 0x61, 0x6b, 0x37, 0x7e, 0x6e, 0x92, 0xd9, 0x53, 0x4c, 0x6a, 0xef, 0xa7, 0x56, 0xf3, 0x08,
	0x8b, 0x96, 0x2c, 0x25, 0x92, 0x14, 0xbd, 0x1b, 0x22, 0xe1, 0x2d, 0x14, 0x31, 0xa9, 0x34, 0xc6,
	0x65, 0x56, 0x67, 0xeb, 0xb9, 0xfc, 0x3b, 0x21, 0xc2, 0x65, 0xe7, 0x34, 0x2d, 0xf3, 0x3a, 0x5b,
	0xcf, 0x24, 0xeb, 0x66, 0x05, 0xe5, 0xbb, 0x19, 0x7a, 0x4b, 0x92, 0xbe, 0x46, 0x8a, 0x09, 0x17,
	0x90, 0x1b, 0xcd, 0x17, 0x4b, 0x99, 0x1b, 0xdd, 0xbc, 0xc1, 0xec, 0x35, 0x68, 0x0a, 0xbf, 0xc1,
	0x4b, 0x7b, 0x0c, 0x5a, 0x7c, 0x80, 0xf9, 0x11, 0x85, 0x27, 0xaf, 0xb6, 0x95, 0x98, 0x60, 0xc5,
	0x01, 0x56, 0x7c, 0x1c, 0x1a, 0xf2, 0xbf, 0xbc, 0xed, 0xe0, 0x9a, 0x27, 0x9f, 0xd5, 0xa0, 0x2d,
	0x05, 0xac, 0xa1, 0x78, 0x0a, 0xa4, 0x12, 0x21, 0x08, 0xe5, 0x8d, 0xe0, 0xb0, 0x3a, 0xd1, 0x78,
	0x07, 0xc5, 0xf4, 0x46, 0x44, 0x76, 0xcf, 0x90, 0xab, 0x1b, 0xf6, 0xce, 0x3f, 0x61, 0x57, 0x30,
	0xc3, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xc7, 0xf3, 0x90, 0x54, 0x01, 0x00, 0x00,
}
