// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateResponse struct {
	CreatedOrder         *Order   `protobuf:"bytes,1,opt,name=createdOrder,proto3" json:"createdOrder,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreatedOrder() *Order {
	if m != nil {
		return m.CreatedOrder
	}
	return nil
}

func (m *CreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "api.Order")
	proto.RegisterType((*CreateResponse)(nil), "api.CreateResponse")
	proto.RegisterType((*Error)(nil), "api.Error")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xd9, 0x6a, 0x57, 0x76, 0xdc, 0xed, 0x61, 0x3c, 0x58, 0x7a, 0xb1, 0xf4, 0xa4, 0x97,
	0x14, 0x2a, 0x1e, 0x3c, 0x8b, 0xe0, 0x4d, 0xc8, 0x3f, 0x48, 0x9b, 0xb1, 0x04, 0xda, 0x26, 0x4c,
	0xa2, 0xbf, 0x5f, 0x9c, 0x22, 0xb4, 0xb7, 0x99, 0x6f, 0x5e, 0x5e, 0xde, 0x83, 0x4b, 0x24, 0xfe,
	0x71, 0x03, 0xa9, 0xc0, 0x3e, 0x79, 0xbc, 0x32, 0xc1, 0x55, 0x0f, 0xa3, 0xf7, 0xe3, 0x44, 0xad,
	0xa0, 0xfe, 0xfb, 0xab, 0x4d, 0x6e, 0xa6, 0x98, 0xcc, 0x1c, 0x56, 0x55, 0x73, 0x0f, 0xf9, 0x27,
	0x5b, 0x62, 0x2c, 0x20, 0x73, 0xb6, 0x3c, 0xd4, 0x87, 0xc7, 0x8b, 0xce, 0x9c, 0x6d, 0x7a, 0x28,
	0xde, 0x98, 0x4c, 0x22, 0x4d, 0x31, 0xf8, 0x25, 0x12, 0x2a, 0x38, 0x0f, 0x42, 0xac, 0xbc, 0x10,
	0xed, 0x6d, 0x07, 0xca, 0x04, 0xa7, 0x84, 0xe8, 0xdd, 0x1d, 0x6b, 0xc8, 0x89, 0xd9, 0x73, 0x99,
	0x6d, 0x84, 0xef, 0x7f, 0x44, 0xaf, 0x87, 0xe6, 0x05, 0x72, 0xd9, 0x11, 0xe1, 0x7a, 0xf0, 0x96,
	0xc4, 0xf2, 0xa4, 0x65, 0xc6, 0x12, 0x6e, 0x66, 0x8a, 0xd1, 0x8c, 0x24, 0x06, 0x27, 0xfd, 0xbf,
	0x76, 0xaf, 0x70, 0x96, 0x1f, 0x3e, 0xcc, 0x62, 0x27, 0x62, 0x7c, 0x82, 0xe3, 0x1a, 0x15, 0x37,
	0x61, 0xaa, 0x3b, 0x99, 0xf7, 0x1d, 0xfa, 0xa3, 0xb4, 0x7e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0xe2, 0x5f, 0xad, 0x2c, 0x01, 0x00, 0x00,
}
